name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Backend Dependencies
        run: |
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Install Frontend Dependencies
        run: |
          pip install --upgrade pip
          pip install -r frontend/requirements.txt

      - name: Run Tests
        run: echo "No tests defined yet"

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend

      
      - name: Build & Push Logger
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/logger ./logger
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/logger

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    steps:
      - name: Send failure email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: GitHub Actions Workflow Failed
          to: kutesumedh388@gmial.com
          from: ${{ secrets.GMAIL_USERNAME }}
          body: The CI/CD pipeline has failed. Please check the Actions tab.